# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 24
Set Width 1200
Set Height 600
Set TypingSpeed 150ms

# Type a command in the terminal.
Type "clerk"
Sleep 100ms

Enter
Sleep 500ms

Type 'clerk todo "Do the dishes"'
Sleep 100ms

Enter
Sleep 500ms

Type 'clerk todo "Tidy room"'
Sleep 100ms

Enter
Sleep 500ms

Type 'clerk todo "Tag new clerk release"'
Sleep 100ms

Enter
Sleep 500ms

Type 'clerk todo "Add OpenBSD release build"'
Sleep 100ms

Type 'clerk list'
Sleep 100ms

Enter
Sleep 500ms

Type 'clerk done 1'
Sleep 100ms

Enter
Sleep 500ms

Type 'clerk list'
Sleep 100ms

Enter
Sleep 500ms

Type 'clerk search release'
Sleep 100ms

Enter
Sleep 500ms

Sleep 5s