name: clerk release
on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    strategy:
      matrix:
        target: [x86_64-linux, aarch64-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - run: echo $GITHUB_REF_NAME > src/.version
      - run: zig build -Drelease-safe=true -Dtarget=${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: clerk-${{matrix.target}}
          path: zig-out/bin/clerk