name: clerk release
on:
  push:
    tags:
      - "v*"

jobs:
  gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: echo -n $GITHUB_REF_NAME > src/.version
      - run: zig build
      - run: echo "zig-out/bin" >> $GITHUB_PATH
      - uses: charmbracelet/vhs-action@v2
        with:
          path: "demo.tape"
      - uses: actions/upload-artifact@v3
        with:
          name: demo-${{ github.ref_name }}.gif
          path: demo.gif
  build_and_release:
    strategy:
      matrix:
        target: [x86_64, aarch64]
        os: [linux, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: echo -n $GITHUB_REF_NAME > src/.version
      - run: zig build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.target }}-${{ matrix.os }}
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os != 'windows' }}
        with:
          name: clerk-${{ github.ref_name }}-${{ matrix.target }}-${{ matrix.os }}
          path: zig-out/bin/clerk
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'windows' }}
        with:
          name: clerk-${{ github.ref_name }}-${{ matrix.target }}-${{ matrix.os }}
          path: zig-out/bin/clerk.exe
