name: clerk release
on:
  push:
    tags:
      - "v*"

jobs:
  gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - run: echo -n $GITHUB_REF_NAME > src/.version
      - run: zig build
      - run: echo "zig-out/bin" >> $GITHUB_PATH
      - uses: charmbracelet/vhs-action@v1
        with:
          path: 'demo.tape'
      - uses: actions/upload-artifact@v3
        with:
          name: demo-${{ github.ref_name }}.gif
          path: demo.gif
  build_and_release:
    strategy:
      matrix:
        target: [x86_64-linux, x86_64-macos, x86_64-windows, aarch64-linux, aarch64-macos, aarch64-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - run: echo -n $GITHUB_REF_NAME > src/.version
      - run: zig build -Drelease-safe=true -Dtarget=${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.target != 'x86_64-windows' }} 
        with:
          name: clerk-${{ github.ref_name }}-${{matrix.target}}
          path: zig-out/bin/clerk
      - uses: actions/upload-artifact@v3
        if: ${{ matrix.target == 'x86_64-windows' }} 
        with:
          name: clerk-${{ github.ref_name }}-${{matrix.target}}
          path: zig-out/bin/clerk.exe
