name: clerk release
on:
  push:
    tags:
      - "v*"

jobs:
  gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2   
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: master
      - run: zig build --fetch
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.16.0
      - run: echo -n $GITHUB_REF_NAME > src/.version
      - run: zig build
      - run: echo "zig-out/bin" >> $GITHUB_PATH
      - name: Create gif # See https://github.com/charmbracelet/vhs-action/issues/459 for why this isn't using the action
        run: |
          sudo apt-get install -y --no-install-recommends ffmpeg ttyd
          go install github.com/charmbracelet/vhs@latest
          ~/go/bin/vhs demo.tape
      - uses: actions/upload-artifact@v4
        with:
          name: demo-${{ github.ref_name }}.gif
          path: demo.gif
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, aarch64]
        os: [linux, macos, windows, freebsd, netbsd, openbsd]
    env:
      EXE_SUFFIX: ${{ matrix.os == 'windows' && '.exe' || '' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: master
      - run: zig build --fetch
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.16.0
      - run: echo -n $GITHUB_REF_NAME > src/.version

      - name: Build clerk
        run: |
          zig build -Doptimize=ReleaseSafe -Dtarget=${{ matrix.target }}-${{ matrix.os }}

      - name: Compress output
        run: |
          zip clerk-${{ github.ref_name }}-${{ matrix.target }}-${{ matrix.os }}.zip zig-out/bin/clerk${{ env.EXE_SUFFIX }} -j

      - uses: actions/upload-artifact@v4
        with:
          name: clerk-${{ github.ref_name }}-${{ matrix.target }}-${{ matrix.os }}.zip
          path: clerk-${{ github.ref_name }}-${{ matrix.target }}-${{ matrix.os }}.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: List artifacts
        run: ls -R ./artifacts
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: |
            artifacts/**/**/*.zip
