name: clerk tests
on:
  push:
    paths:
      - src/**
      - lib/**
      - build.zig
      - build.zig.zon
      - .github/workflows/test.yaml

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64, aarch64]
        os: [linux, macos, windows, freebsd, netbsd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v2.0.5
      - run: zig build -Dtarget=${{ matrix.target }}-${{ matrix.os }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v2.0.5
      - run: zig build
      - run: zig-out/bin/clerk
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v2.0.5
      - run: zig fmt --check src/*.zig
