name: clerk tests
on:
  push:
    paths:
      - src/**
      - lib/**
      - build.zig
      - .github/workflows/test.yaml

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64, aarch64]
        os: [linux, macos, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build -Dtarget=${{ matrix.target }}-${{ matrix.os }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build
      - run: zig-out/bin/clerk
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check src/*.zig
