name: clerk tests
on:
  push:
    paths:
      - src/**
      - lib/**
      - build.zig
      - .github/workflows/test.yaml

jobs:
  build:
    strategy:
      matrix:
        target: [x86_64-linux, x86_64-macos, x86_64-windows, aarch64-linux, aarch64-macos, aarch64-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - run: zig build -Dtarget=${{ matrix.target }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0
      - run: zig fmt --check src/*.zig
